# 服务端口
server:
  port: 8080

spring:
    # 数据库配置
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    # 应用名称
    application:
        name: demo
    # 文件存储 配置文档：https://spring-file-storage.xuyanwu.cn
    file-storage:
        default-platform: qiniu-kodo-1
        qiniu-kodo:
            - platform: qiniu-kodo-1
              enable-storage: true
              access-key: Uxv7S8cYoVvzznmVcWegxzV-ihWvqjDR5iV3Joph
              secret-key: jM_VBuv9TODxZ0M1F5hPUtYkyGhjutKQXzRSe93Q
              bucket-name: md-picture-cxy-csx
              domain: https://qiniu.cxy-csx.top/

    # Redis配置
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 6000
      jedis:
        pool:
          max-active: 1000
          max-wait: -1
          max-idle: 10
          min-idle: 5

# Sa-Token 配置文档: https://sa-token.cc
sa-token:
  token-name: token
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true

# forest 配置文档: https://forest.dtflyx.com
forest:
  max-connections: 1000        # 连接池最大连接数
  connect-timeout: 3000        # 连接超时时间，单位为毫秒
  read-timeout: 3000           # 数据读取超时时间，单位为毫秒


# Mybatis-Plus 配置文档: https://baomidou.com
mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    global-config:
        db-config:
            table-prefix: t_
    configuration:
        default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

# knife4j 配置文档: https://doc.xiaominfo.com
knife4j:
  enable: true


# sms 配置文档: https://wind.kim/
sms:
  tencent:
    #腾讯云的accessKey
    accessKeyId: AKIDRgfiZH0FPO8g3LLL0RbolcIpGvrYpmCN
    #腾讯云的accessKeySecret
    accessKeySecret: DBt99ybxeebKnfLm3iAyf6rNHEwqUUhe
    #短信签名
    signature: 程序员陈师兄个人网
    #模板ID 用于发送固定模板短信使用
    templateId: 1883314
    #模板变量 上述模板的变量
    templateName: 1
    #请求超时时间 默认60秒
    connTimeout: 60
    #短信sdkAppId
    sdkAppId: 1400844272
#    #地域信息默认为 ap-guangzhou 如无特殊改变可不用设置
#    territory: ap-guangzhou
#    #请求地址默认为 sms.tencentcloudapi.com 如无特殊改变可不用设置
#    requestUrl: sms.tencentcloudapi.com
#    #接口名称默认为 SendSms 如无特殊改变可不用设置
#    action: SendSms
#    #接口版本默认为 2021-01-11 如无特殊改变可不用设置
#    version: 2021-01-11



logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
