# 服务端口
server:
  port: 8080

spring:
    # 数据库配置
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    # 应用名称
    application:
        name: demo
    # 文件存储配置
    file-storage:
        default-platform: qiniu-kodo-1
        qiniu-kodo:
            - platform: qiniu-kodo-1
              enable-storage: true
              access-key: Uxv7S8cYoVvzznmVcWegxzV-ihWvqjDR5iV3Joph
              secret-key: jM_VBuv9TODxZ0M1F5hPUtYkyGhjutKQXzRSe93Q
              bucket-name: md-picture-cxy-csx
              domain: https://qiniu.cxy-csx.top/


    redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      timeout: 6000
      # Redis服务器连接密码（默认为空）
      #      password:
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接




mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    global-config:
        db-config:
            table-prefix: t_
    configuration:
        default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler










